name: Sync to Hugging Face Hub
on:
  push:
    branches: [main] # لو الفرع الرئيسي عندك اسمه master غيره لـ master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: 3Alaaa/advanced-numerical-calculator
          hf_token: ${{ secrets.HF_TOKEN }}
          space_sdk: streamlit
